# Generated by Django 4.2.26 on 2025-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='ciclo_terminado',
            field=models.BooleanField(default=False, help_text='Indica si el ciclo ha finalizado. Las notas quedan bloqueadas.'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fecha_fin_ciclo',
            field=models.DateField(blank=True, help_text='Fecha de fin del ciclo académico', null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fecha_inicio_ciclo',
            field=models.DateField(blank=True, help_text='Fecha de inicio del ciclo académico', null=True),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_fin_matricula',
            field=models.DateField(help_text='Fecha de fin del período de matrícula'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_inicio_matricula',
            field=models.DateField(help_text='Fecha de inicio del período de matrícula'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='matricula_abierta',
            field=models.BooleanField(default=True, help_text='Indica si la matrícula está abierta'),
        ),
    ]
